version: '3'
services:
    colorsservice:
        build: ./ColorsService
        ports:
         - 4567:4567
        depends_on:
         - db
        networks:
         - color-network

    db:
        build: ./database
        networks:
         - color-network

    front:
        build: ./frontend
        depends_on:
         - colorsservice
        networks:
         - color-network

networks:
  color-network:
    driver: bridge